//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceTaxiSoap")]
    public interface WebServiceTaxiSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем driver из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateDriver", ReplyAction="*")]
        DClient.ServiceReference1.RegistrateDriverResponse RegistrateDriver(DClient.ServiceReference1.RegistrateDriverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateDriver", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.RegistrateDriverResponse> RegistrateDriverAsync(DClient.ServiceReference1.RegistrateDriverRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем customer из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateCustomer", ReplyAction="*")]
        DClient.ServiceReference1.RegistrateCustomerResponse RegistrateCustomer(DClient.ServiceReference1.RegistrateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.RegistrateCustomerResponse> RegistrateCustomerAsync(DClient.ServiceReference1.RegistrateCustomerRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем authorization из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        DClient.ServiceReference1.AuthorizeResponse Authorize(DClient.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.AuthorizeResponse> AuthorizeAsync(DClient.ServiceReference1.AuthorizeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetListOfOrdersResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOfOrders", ReplyAction="*")]
        DClient.ServiceReference1.GetListOfOrdersResponse GetListOfOrders(DClient.ServiceReference1.GetListOfOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOfOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.GetListOfOrdersResponse> GetListOfOrdersAsync(DClient.ServiceReference1.GetListOfOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        void GetOrder(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        System.Threading.Tasks.Task GetOrderAsync(System.Guid idDriver, System.Guid idOrder);
        
        // CODEGEN: Контракт генерации сообщений с именем order из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        DClient.ServiceReference1.CreateOrderResponse CreateOrder(DClient.ServiceReference1.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.CreateOrderResponse> CreateOrderAsync(DClient.ServiceReference1.CreateOrderRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ShowOrderResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowOrder", ReplyAction="*")]
        DClient.ServiceReference1.ShowOrderResponse ShowOrder(DClient.ServiceReference1.ShowOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.ShowOrderResponse> ShowOrderAsync(DClient.ServiceReference1.ShowOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellationOfOrder", ReplyAction="*")]
        void CancellationOfOrder(System.Guid idClient, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellationOfOrder", ReplyAction="*")]
        System.Threading.Tasks.Task CancellationOfOrderAsync(System.Guid idClient, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartTrip", ReplyAction="*")]
        void StartTrip(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartTrip", ReplyAction="*")]
        System.Threading.Tasks.Task StartTripAsync(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishTrip", ReplyAction="*")]
        void FinishTrip(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishTrip", ReplyAction="*")]
        System.Threading.Tasks.Task FinishTripAsync(System.Guid idDriver, System.Guid idOrder);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDriverNumberResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDriverNumber", ReplyAction="*")]
        DClient.ServiceReference1.GetDriverNumberResponse GetDriverNumber(DClient.ServiceReference1.GetDriverNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDriverNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.GetDriverNumberResponse> GetDriverNumberAsync(DClient.ServiceReference1.GetDriverNumberRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindCustomerResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomer", ReplyAction="*")]
        DClient.ServiceReference1.FindCustomerResponse FindCustomer(DClient.ServiceReference1.FindCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.FindCustomerResponse> FindCustomerAsync(DClient.ServiceReference1.FindCustomerRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindDriverResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDriver", ReplyAction="*")]
        DClient.ServiceReference1.FindDriverResponse FindDriver(DClient.ServiceReference1.FindDriverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDriver", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.FindDriverResponse> FindDriverAsync(DClient.ServiceReference1.FindDriverRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindAuthResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAuth", ReplyAction="*")]
        DClient.ServiceReference1.FindAuthResponse FindAuth(DClient.ServiceReference1.FindAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.FindAuthResponse> FindAuthAsync(DClient.ServiceReference1.FindAuthRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем auth из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCustomerProfile", ReplyAction="*")]
        DClient.ServiceReference1.EditCustomerProfileResponse EditCustomerProfile(DClient.ServiceReference1.EditCustomerProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCustomerProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.EditCustomerProfileResponse> EditCustomerProfileAsync(DClient.ServiceReference1.EditCustomerProfileRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем auth из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditDriverProfile", ReplyAction="*")]
        DClient.ServiceReference1.EditDriverProfileResponse EditDriverProfile(DClient.ServiceReference1.EditDriverProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditDriverProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<DClient.ServiceReference1.EditDriverProfileResponse> EditDriverProfileAsync(DClient.ServiceReference1.EditDriverProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateDriverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateDriver", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.RegistrateDriverRequestBody Body;
        
        public RegistrateDriverRequest() {
        }
        
        public RegistrateDriverRequest(DClient.ServiceReference1.RegistrateDriverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateDriverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string driver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authorization;
        
        public RegistrateDriverRequestBody() {
        }
        
        public RegistrateDriverRequestBody(string driver, string authorization) {
            this.driver = driver;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateDriverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateDriverResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.RegistrateDriverResponseBody Body;
        
        public RegistrateDriverResponse() {
        }
        
        public RegistrateDriverResponse(DClient.ServiceReference1.RegistrateDriverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateDriverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrateDriverResult;
        
        public RegistrateDriverResponseBody() {
        }
        
        public RegistrateDriverResponseBody(bool RegistrateDriverResult) {
            this.RegistrateDriverResult = RegistrateDriverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.RegistrateCustomerRequestBody Body;
        
        public RegistrateCustomerRequest() {
        }
        
        public RegistrateCustomerRequest(DClient.ServiceReference1.RegistrateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authorization;
        
        public RegistrateCustomerRequestBody() {
        }
        
        public RegistrateCustomerRequestBody(string customer, string authorization) {
            this.customer = customer;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.RegistrateCustomerResponseBody Body;
        
        public RegistrateCustomerResponse() {
        }
        
        public RegistrateCustomerResponse(DClient.ServiceReference1.RegistrateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrateCustomerResult;
        
        public RegistrateCustomerResponseBody() {
        }
        
        public RegistrateCustomerResponseBody(bool RegistrateCustomerResult) {
            this.RegistrateCustomerResult = RegistrateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorize", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.AuthorizeRequestBody Body;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(DClient.ServiceReference1.AuthorizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorization;
        
        public AuthorizeRequestBody() {
        }
        
        public AuthorizeRequestBody(string authorization) {
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.AuthorizeResponseBody Body;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(DClient.ServiceReference1.AuthorizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid AuthorizeResult;
        
        public AuthorizeResponseBody() {
        }
        
        public AuthorizeResponseBody(System.Guid AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrders", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.GetListOfOrdersRequestBody Body;
        
        public GetListOfOrdersRequest() {
        }
        
        public GetListOfOrdersRequest(DClient.ServiceReference1.GetListOfOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListOfOrdersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int role;
        
        public GetListOfOrdersRequestBody() {
        }
        
        public GetListOfOrdersRequestBody(System.Guid idClient, int role) {
            this.idClient = idClient;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.GetListOfOrdersResponseBody Body;
        
        public GetListOfOrdersResponse() {
        }
        
        public GetListOfOrdersResponse(DClient.ServiceReference1.GetListOfOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListOfOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListOfOrdersResult;
        
        public GetListOfOrdersResponseBody() {
        }
        
        public GetListOfOrdersResponseBody(string GetListOfOrdersResult) {
            this.GetListOfOrdersResult = GetListOfOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrder", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.CreateOrderRequestBody Body;
        
        public CreateOrderRequest() {
        }
        
        public CreateOrderRequest(DClient.ServiceReference1.CreateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string order;
        
        public CreateOrderRequestBody() {
        }
        
        public CreateOrderRequestBody(string order) {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.CreateOrderResponseBody Body;
        
        public CreateOrderResponse() {
        }
        
        public CreateOrderResponse(DClient.ServiceReference1.CreateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateOrderResponseBody {
        
        public CreateOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowOrder", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.ShowOrderRequestBody Body;
        
        public ShowOrderRequest() {
        }
        
        public ShowOrderRequest(DClient.ServiceReference1.ShowOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idClient;
        
        public ShowOrderRequestBody() {
        }
        
        public ShowOrderRequestBody(System.Guid idClient) {
            this.idClient = idClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.ShowOrderResponseBody Body;
        
        public ShowOrderResponse() {
        }
        
        public ShowOrderResponse(DClient.ServiceReference1.ShowOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowOrderResult;
        
        public ShowOrderResponseBody() {
        }
        
        public ShowOrderResponseBody(string ShowOrderResult) {
            this.ShowOrderResult = ShowOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDriverNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDriverNumber", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.GetDriverNumberRequestBody Body;
        
        public GetDriverNumberRequest() {
        }
        
        public GetDriverNumberRequest(DClient.ServiceReference1.GetDriverNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDriverNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idOrder;
        
        public GetDriverNumberRequestBody() {
        }
        
        public GetDriverNumberRequestBody(System.Guid idOrder) {
            this.idOrder = idOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDriverNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDriverNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.GetDriverNumberResponseBody Body;
        
        public GetDriverNumberResponse() {
        }
        
        public GetDriverNumberResponse(DClient.ServiceReference1.GetDriverNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDriverNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDriverNumberResult;
        
        public GetDriverNumberResponseBody() {
        }
        
        public GetDriverNumberResponseBody(string GetDriverNumberResult) {
            this.GetDriverNumberResult = GetDriverNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCustomer", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.FindCustomerRequestBody Body;
        
        public FindCustomerRequest() {
        }
        
        public FindCustomerRequest(DClient.ServiceReference1.FindCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idCustomer;
        
        public FindCustomerRequestBody() {
        }
        
        public FindCustomerRequestBody(System.Guid idCustomer) {
            this.idCustomer = idCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.FindCustomerResponseBody Body;
        
        public FindCustomerResponse() {
        }
        
        public FindCustomerResponse(DClient.ServiceReference1.FindCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindCustomerResult;
        
        public FindCustomerResponseBody() {
        }
        
        public FindCustomerResponseBody(string FindCustomerResult) {
            this.FindCustomerResult = FindCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDriverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDriver", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.FindDriverRequestBody Body;
        
        public FindDriverRequest() {
        }
        
        public FindDriverRequest(DClient.ServiceReference1.FindDriverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDriverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idDriver;
        
        public FindDriverRequestBody() {
        }
        
        public FindDriverRequestBody(System.Guid idDriver) {
            this.idDriver = idDriver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDriverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDriverResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.FindDriverResponseBody Body;
        
        public FindDriverResponse() {
        }
        
        public FindDriverResponse(DClient.ServiceReference1.FindDriverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDriverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindDriverResult;
        
        public FindDriverResponseBody() {
        }
        
        public FindDriverResponseBody(string FindDriverResult) {
            this.FindDriverResult = FindDriverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAuth", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.FindAuthRequestBody Body;
        
        public FindAuthRequest() {
        }
        
        public FindAuthRequest(DClient.ServiceReference1.FindAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public FindAuthRequestBody() {
        }
        
        public FindAuthRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.FindAuthResponseBody Body;
        
        public FindAuthResponse() {
        }
        
        public FindAuthResponse(DClient.ServiceReference1.FindAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindAuthResult;
        
        public FindAuthResponseBody() {
        }
        
        public FindAuthResponseBody(string FindAuthResult) {
            this.FindAuthResult = FindAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCustomerProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCustomerProfile", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.EditCustomerProfileRequestBody Body;
        
        public EditCustomerProfileRequest() {
        }
        
        public EditCustomerProfileRequest(DClient.ServiceReference1.EditCustomerProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCustomerProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer;
        
        public EditCustomerProfileRequestBody() {
        }
        
        public EditCustomerProfileRequestBody(string auth, string customer) {
            this.auth = auth;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCustomerProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCustomerProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.EditCustomerProfileResponseBody Body;
        
        public EditCustomerProfileResponse() {
        }
        
        public EditCustomerProfileResponse(DClient.ServiceReference1.EditCustomerProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCustomerProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditCustomerProfileResult;
        
        public EditCustomerProfileResponseBody() {
        }
        
        public EditCustomerProfileResponseBody(bool EditCustomerProfileResult) {
            this.EditCustomerProfileResult = EditCustomerProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDriverProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDriverProfile", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.EditDriverProfileRequestBody Body;
        
        public EditDriverProfileRequest() {
        }
        
        public EditDriverProfileRequest(DClient.ServiceReference1.EditDriverProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditDriverProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string driver;
        
        public EditDriverProfileRequestBody() {
        }
        
        public EditDriverProfileRequestBody(string auth, string driver) {
            this.auth = auth;
            this.driver = driver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDriverProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDriverProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public DClient.ServiceReference1.EditDriverProfileResponseBody Body;
        
        public EditDriverProfileResponse() {
        }
        
        public EditDriverProfileResponse(DClient.ServiceReference1.EditDriverProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditDriverProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditDriverProfileResult;
        
        public EditDriverProfileResponseBody() {
        }
        
        public EditDriverProfileResponseBody(bool EditDriverProfileResult) {
            this.EditDriverProfileResult = EditDriverProfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTaxiSoapChannel : DClient.ServiceReference1.WebServiceTaxiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTaxiSoapClient : System.ServiceModel.ClientBase<DClient.ServiceReference1.WebServiceTaxiSoap>, DClient.ServiceReference1.WebServiceTaxiSoap {
        
        public WebServiceTaxiSoapClient() {
        }
        
        public WebServiceTaxiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTaxiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTaxiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTaxiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.RegistrateDriverResponse DClient.ServiceReference1.WebServiceTaxiSoap.RegistrateDriver(DClient.ServiceReference1.RegistrateDriverRequest request) {
            return base.Channel.RegistrateDriver(request);
        }
        
        public bool RegistrateDriver(string driver, string authorization) {
            DClient.ServiceReference1.RegistrateDriverRequest inValue = new DClient.ServiceReference1.RegistrateDriverRequest();
            inValue.Body = new DClient.ServiceReference1.RegistrateDriverRequestBody();
            inValue.Body.driver = driver;
            inValue.Body.authorization = authorization;
            DClient.ServiceReference1.RegistrateDriverResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateDriver(inValue);
            return retVal.Body.RegistrateDriverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.RegistrateDriverResponse> DClient.ServiceReference1.WebServiceTaxiSoap.RegistrateDriverAsync(DClient.ServiceReference1.RegistrateDriverRequest request) {
            return base.Channel.RegistrateDriverAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.RegistrateDriverResponse> RegistrateDriverAsync(string driver, string authorization) {
            DClient.ServiceReference1.RegistrateDriverRequest inValue = new DClient.ServiceReference1.RegistrateDriverRequest();
            inValue.Body = new DClient.ServiceReference1.RegistrateDriverRequestBody();
            inValue.Body.driver = driver;
            inValue.Body.authorization = authorization;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateDriverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.RegistrateCustomerResponse DClient.ServiceReference1.WebServiceTaxiSoap.RegistrateCustomer(DClient.ServiceReference1.RegistrateCustomerRequest request) {
            return base.Channel.RegistrateCustomer(request);
        }
        
        public bool RegistrateCustomer(string customer, string authorization) {
            DClient.ServiceReference1.RegistrateCustomerRequest inValue = new DClient.ServiceReference1.RegistrateCustomerRequest();
            inValue.Body = new DClient.ServiceReference1.RegistrateCustomerRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.authorization = authorization;
            DClient.ServiceReference1.RegistrateCustomerResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateCustomer(inValue);
            return retVal.Body.RegistrateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.RegistrateCustomerResponse> DClient.ServiceReference1.WebServiceTaxiSoap.RegistrateCustomerAsync(DClient.ServiceReference1.RegistrateCustomerRequest request) {
            return base.Channel.RegistrateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.RegistrateCustomerResponse> RegistrateCustomerAsync(string customer, string authorization) {
            DClient.ServiceReference1.RegistrateCustomerRequest inValue = new DClient.ServiceReference1.RegistrateCustomerRequest();
            inValue.Body = new DClient.ServiceReference1.RegistrateCustomerRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.authorization = authorization;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.AuthorizeResponse DClient.ServiceReference1.WebServiceTaxiSoap.Authorize(DClient.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public System.Guid Authorize(string authorization) {
            DClient.ServiceReference1.AuthorizeRequest inValue = new DClient.ServiceReference1.AuthorizeRequest();
            inValue.Body = new DClient.ServiceReference1.AuthorizeRequestBody();
            inValue.Body.authorization = authorization;
            DClient.ServiceReference1.AuthorizeResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).Authorize(inValue);
            return retVal.Body.AuthorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.AuthorizeResponse> DClient.ServiceReference1.WebServiceTaxiSoap.AuthorizeAsync(DClient.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.AuthorizeResponse> AuthorizeAsync(string authorization) {
            DClient.ServiceReference1.AuthorizeRequest inValue = new DClient.ServiceReference1.AuthorizeRequest();
            inValue.Body = new DClient.ServiceReference1.AuthorizeRequestBody();
            inValue.Body.authorization = authorization;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).AuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.GetListOfOrdersResponse DClient.ServiceReference1.WebServiceTaxiSoap.GetListOfOrders(DClient.ServiceReference1.GetListOfOrdersRequest request) {
            return base.Channel.GetListOfOrders(request);
        }
        
        public string GetListOfOrders(System.Guid idClient, int role) {
            DClient.ServiceReference1.GetListOfOrdersRequest inValue = new DClient.ServiceReference1.GetListOfOrdersRequest();
            inValue.Body = new DClient.ServiceReference1.GetListOfOrdersRequestBody();
            inValue.Body.idClient = idClient;
            inValue.Body.role = role;
            DClient.ServiceReference1.GetListOfOrdersResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetListOfOrders(inValue);
            return retVal.Body.GetListOfOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.GetListOfOrdersResponse> DClient.ServiceReference1.WebServiceTaxiSoap.GetListOfOrdersAsync(DClient.ServiceReference1.GetListOfOrdersRequest request) {
            return base.Channel.GetListOfOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.GetListOfOrdersResponse> GetListOfOrdersAsync(System.Guid idClient, int role) {
            DClient.ServiceReference1.GetListOfOrdersRequest inValue = new DClient.ServiceReference1.GetListOfOrdersRequest();
            inValue.Body = new DClient.ServiceReference1.GetListOfOrdersRequestBody();
            inValue.Body.idClient = idClient;
            inValue.Body.role = role;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetListOfOrdersAsync(inValue);
        }
        
        public void GetOrder(System.Guid idDriver, System.Guid idOrder) {
            base.Channel.GetOrder(idDriver, idOrder);
        }
        
        public System.Threading.Tasks.Task GetOrderAsync(System.Guid idDriver, System.Guid idOrder) {
            return base.Channel.GetOrderAsync(idDriver, idOrder);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.CreateOrderResponse DClient.ServiceReference1.WebServiceTaxiSoap.CreateOrder(DClient.ServiceReference1.CreateOrderRequest request) {
            return base.Channel.CreateOrder(request);
        }
        
        public void CreateOrder(string order) {
            DClient.ServiceReference1.CreateOrderRequest inValue = new DClient.ServiceReference1.CreateOrderRequest();
            inValue.Body = new DClient.ServiceReference1.CreateOrderRequestBody();
            inValue.Body.order = order;
            DClient.ServiceReference1.CreateOrderResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).CreateOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.CreateOrderResponse> DClient.ServiceReference1.WebServiceTaxiSoap.CreateOrderAsync(DClient.ServiceReference1.CreateOrderRequest request) {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.CreateOrderResponse> CreateOrderAsync(string order) {
            DClient.ServiceReference1.CreateOrderRequest inValue = new DClient.ServiceReference1.CreateOrderRequest();
            inValue.Body = new DClient.ServiceReference1.CreateOrderRequestBody();
            inValue.Body.order = order;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).CreateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.ShowOrderResponse DClient.ServiceReference1.WebServiceTaxiSoap.ShowOrder(DClient.ServiceReference1.ShowOrderRequest request) {
            return base.Channel.ShowOrder(request);
        }
        
        public string ShowOrder(System.Guid idClient) {
            DClient.ServiceReference1.ShowOrderRequest inValue = new DClient.ServiceReference1.ShowOrderRequest();
            inValue.Body = new DClient.ServiceReference1.ShowOrderRequestBody();
            inValue.Body.idClient = idClient;
            DClient.ServiceReference1.ShowOrderResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).ShowOrder(inValue);
            return retVal.Body.ShowOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.ShowOrderResponse> DClient.ServiceReference1.WebServiceTaxiSoap.ShowOrderAsync(DClient.ServiceReference1.ShowOrderRequest request) {
            return base.Channel.ShowOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.ShowOrderResponse> ShowOrderAsync(System.Guid idClient) {
            DClient.ServiceReference1.ShowOrderRequest inValue = new DClient.ServiceReference1.ShowOrderRequest();
            inValue.Body = new DClient.ServiceReference1.ShowOrderRequestBody();
            inValue.Body.idClient = idClient;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).ShowOrderAsync(inValue);
        }
        
        public void CancellationOfOrder(System.Guid idClient, System.Guid idOrder) {
            base.Channel.CancellationOfOrder(idClient, idOrder);
        }
        
        public System.Threading.Tasks.Task CancellationOfOrderAsync(System.Guid idClient, System.Guid idOrder) {
            return base.Channel.CancellationOfOrderAsync(idClient, idOrder);
        }
        
        public void StartTrip(System.Guid idDriver, System.Guid idOrder) {
            base.Channel.StartTrip(idDriver, idOrder);
        }
        
        public System.Threading.Tasks.Task StartTripAsync(System.Guid idDriver, System.Guid idOrder) {
            return base.Channel.StartTripAsync(idDriver, idOrder);
        }
        
        public void FinishTrip(System.Guid idDriver, System.Guid idOrder) {
            base.Channel.FinishTrip(idDriver, idOrder);
        }
        
        public System.Threading.Tasks.Task FinishTripAsync(System.Guid idDriver, System.Guid idOrder) {
            return base.Channel.FinishTripAsync(idDriver, idOrder);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.GetDriverNumberResponse DClient.ServiceReference1.WebServiceTaxiSoap.GetDriverNumber(DClient.ServiceReference1.GetDriverNumberRequest request) {
            return base.Channel.GetDriverNumber(request);
        }
        
        public string GetDriverNumber(System.Guid idOrder) {
            DClient.ServiceReference1.GetDriverNumberRequest inValue = new DClient.ServiceReference1.GetDriverNumberRequest();
            inValue.Body = new DClient.ServiceReference1.GetDriverNumberRequestBody();
            inValue.Body.idOrder = idOrder;
            DClient.ServiceReference1.GetDriverNumberResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetDriverNumber(inValue);
            return retVal.Body.GetDriverNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.GetDriverNumberResponse> DClient.ServiceReference1.WebServiceTaxiSoap.GetDriverNumberAsync(DClient.ServiceReference1.GetDriverNumberRequest request) {
            return base.Channel.GetDriverNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.GetDriverNumberResponse> GetDriverNumberAsync(System.Guid idOrder) {
            DClient.ServiceReference1.GetDriverNumberRequest inValue = new DClient.ServiceReference1.GetDriverNumberRequest();
            inValue.Body = new DClient.ServiceReference1.GetDriverNumberRequestBody();
            inValue.Body.idOrder = idOrder;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetDriverNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.FindCustomerResponse DClient.ServiceReference1.WebServiceTaxiSoap.FindCustomer(DClient.ServiceReference1.FindCustomerRequest request) {
            return base.Channel.FindCustomer(request);
        }
        
        public string FindCustomer(System.Guid idCustomer) {
            DClient.ServiceReference1.FindCustomerRequest inValue = new DClient.ServiceReference1.FindCustomerRequest();
            inValue.Body = new DClient.ServiceReference1.FindCustomerRequestBody();
            inValue.Body.idCustomer = idCustomer;
            DClient.ServiceReference1.FindCustomerResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindCustomer(inValue);
            return retVal.Body.FindCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.FindCustomerResponse> DClient.ServiceReference1.WebServiceTaxiSoap.FindCustomerAsync(DClient.ServiceReference1.FindCustomerRequest request) {
            return base.Channel.FindCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.FindCustomerResponse> FindCustomerAsync(System.Guid idCustomer) {
            DClient.ServiceReference1.FindCustomerRequest inValue = new DClient.ServiceReference1.FindCustomerRequest();
            inValue.Body = new DClient.ServiceReference1.FindCustomerRequestBody();
            inValue.Body.idCustomer = idCustomer;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.FindDriverResponse DClient.ServiceReference1.WebServiceTaxiSoap.FindDriver(DClient.ServiceReference1.FindDriverRequest request) {
            return base.Channel.FindDriver(request);
        }
        
        public string FindDriver(System.Guid idDriver) {
            DClient.ServiceReference1.FindDriverRequest inValue = new DClient.ServiceReference1.FindDriverRequest();
            inValue.Body = new DClient.ServiceReference1.FindDriverRequestBody();
            inValue.Body.idDriver = idDriver;
            DClient.ServiceReference1.FindDriverResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindDriver(inValue);
            return retVal.Body.FindDriverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.FindDriverResponse> DClient.ServiceReference1.WebServiceTaxiSoap.FindDriverAsync(DClient.ServiceReference1.FindDriverRequest request) {
            return base.Channel.FindDriverAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.FindDriverResponse> FindDriverAsync(System.Guid idDriver) {
            DClient.ServiceReference1.FindDriverRequest inValue = new DClient.ServiceReference1.FindDriverRequest();
            inValue.Body = new DClient.ServiceReference1.FindDriverRequestBody();
            inValue.Body.idDriver = idDriver;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindDriverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.FindAuthResponse DClient.ServiceReference1.WebServiceTaxiSoap.FindAuth(DClient.ServiceReference1.FindAuthRequest request) {
            return base.Channel.FindAuth(request);
        }
        
        public string FindAuth(System.Guid id) {
            DClient.ServiceReference1.FindAuthRequest inValue = new DClient.ServiceReference1.FindAuthRequest();
            inValue.Body = new DClient.ServiceReference1.FindAuthRequestBody();
            inValue.Body.id = id;
            DClient.ServiceReference1.FindAuthResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindAuth(inValue);
            return retVal.Body.FindAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.FindAuthResponse> DClient.ServiceReference1.WebServiceTaxiSoap.FindAuthAsync(DClient.ServiceReference1.FindAuthRequest request) {
            return base.Channel.FindAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.FindAuthResponse> FindAuthAsync(System.Guid id) {
            DClient.ServiceReference1.FindAuthRequest inValue = new DClient.ServiceReference1.FindAuthRequest();
            inValue.Body = new DClient.ServiceReference1.FindAuthRequestBody();
            inValue.Body.id = id;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.EditCustomerProfileResponse DClient.ServiceReference1.WebServiceTaxiSoap.EditCustomerProfile(DClient.ServiceReference1.EditCustomerProfileRequest request) {
            return base.Channel.EditCustomerProfile(request);
        }
        
        public bool EditCustomerProfile(string auth, string customer) {
            DClient.ServiceReference1.EditCustomerProfileRequest inValue = new DClient.ServiceReference1.EditCustomerProfileRequest();
            inValue.Body = new DClient.ServiceReference1.EditCustomerProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.customer = customer;
            DClient.ServiceReference1.EditCustomerProfileResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditCustomerProfile(inValue);
            return retVal.Body.EditCustomerProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.EditCustomerProfileResponse> DClient.ServiceReference1.WebServiceTaxiSoap.EditCustomerProfileAsync(DClient.ServiceReference1.EditCustomerProfileRequest request) {
            return base.Channel.EditCustomerProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.EditCustomerProfileResponse> EditCustomerProfileAsync(string auth, string customer) {
            DClient.ServiceReference1.EditCustomerProfileRequest inValue = new DClient.ServiceReference1.EditCustomerProfileRequest();
            inValue.Body = new DClient.ServiceReference1.EditCustomerProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.customer = customer;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditCustomerProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DClient.ServiceReference1.EditDriverProfileResponse DClient.ServiceReference1.WebServiceTaxiSoap.EditDriverProfile(DClient.ServiceReference1.EditDriverProfileRequest request) {
            return base.Channel.EditDriverProfile(request);
        }
        
        public bool EditDriverProfile(string auth, string driver) {
            DClient.ServiceReference1.EditDriverProfileRequest inValue = new DClient.ServiceReference1.EditDriverProfileRequest();
            inValue.Body = new DClient.ServiceReference1.EditDriverProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.driver = driver;
            DClient.ServiceReference1.EditDriverProfileResponse retVal = ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditDriverProfile(inValue);
            return retVal.Body.EditDriverProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DClient.ServiceReference1.EditDriverProfileResponse> DClient.ServiceReference1.WebServiceTaxiSoap.EditDriverProfileAsync(DClient.ServiceReference1.EditDriverProfileRequest request) {
            return base.Channel.EditDriverProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DClient.ServiceReference1.EditDriverProfileResponse> EditDriverProfileAsync(string auth, string driver) {
            DClient.ServiceReference1.EditDriverProfileRequest inValue = new DClient.ServiceReference1.EditDriverProfileRequest();
            inValue.Body = new DClient.ServiceReference1.EditDriverProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.driver = driver;
            return ((DClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditDriverProfileAsync(inValue);
        }
    }
}
