//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceTaxiSoap")]
    public interface WebServiceTaxiSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем driver из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateDriver", ReplyAction="*")]
        WebClient.ServiceReference1.RegistrateDriverResponse RegistrateDriver(WebClient.ServiceReference1.RegistrateDriverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateDriver", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.RegistrateDriverResponse> RegistrateDriverAsync(WebClient.ServiceReference1.RegistrateDriverRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем customer из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateCustomer", ReplyAction="*")]
        WebClient.ServiceReference1.RegistrateCustomerResponse RegistrateCustomer(WebClient.ServiceReference1.RegistrateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.RegistrateCustomerResponse> RegistrateCustomerAsync(WebClient.ServiceReference1.RegistrateCustomerRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем authorization из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        WebClient.ServiceReference1.AuthorizeResponse Authorize(WebClient.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.AuthorizeResponse> AuthorizeAsync(WebClient.ServiceReference1.AuthorizeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetListOfOrdersResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOfOrders", ReplyAction="*")]
        WebClient.ServiceReference1.GetListOfOrdersResponse GetListOfOrders(WebClient.ServiceReference1.GetListOfOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListOfOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.GetListOfOrdersResponse> GetListOfOrdersAsync(WebClient.ServiceReference1.GetListOfOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        void GetOrder(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        System.Threading.Tasks.Task GetOrderAsync(System.Guid idDriver, System.Guid idOrder);
        
        // CODEGEN: Контракт генерации сообщений с именем order из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        WebClient.ServiceReference1.CreateOrderResponse CreateOrder(WebClient.ServiceReference1.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.CreateOrderResponse> CreateOrderAsync(WebClient.ServiceReference1.CreateOrderRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ShowOrderResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowOrder", ReplyAction="*")]
        WebClient.ServiceReference1.ShowOrderResponse ShowOrder(WebClient.ServiceReference1.ShowOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ShowOrderResponse> ShowOrderAsync(WebClient.ServiceReference1.ShowOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellationOfOrder", ReplyAction="*")]
        void CancellationOfOrder(System.Guid idClient, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellationOfOrder", ReplyAction="*")]
        System.Threading.Tasks.Task CancellationOfOrderAsync(System.Guid idClient, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartTrip", ReplyAction="*")]
        void StartTrip(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartTrip", ReplyAction="*")]
        System.Threading.Tasks.Task StartTripAsync(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishTrip", ReplyAction="*")]
        void FinishTrip(System.Guid idDriver, System.Guid idOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishTrip", ReplyAction="*")]
        System.Threading.Tasks.Task FinishTripAsync(System.Guid idDriver, System.Guid idOrder);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDriverNumberResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDriverNumber", ReplyAction="*")]
        WebClient.ServiceReference1.GetDriverNumberResponse GetDriverNumber(WebClient.ServiceReference1.GetDriverNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDriverNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.GetDriverNumberResponse> GetDriverNumberAsync(WebClient.ServiceReference1.GetDriverNumberRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindCustomerResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomer", ReplyAction="*")]
        WebClient.ServiceReference1.FindCustomerResponse FindCustomer(WebClient.ServiceReference1.FindCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindCustomerResponse> FindCustomerAsync(WebClient.ServiceReference1.FindCustomerRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindDriverResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDriver", ReplyAction="*")]
        WebClient.ServiceReference1.FindDriverResponse FindDriver(WebClient.ServiceReference1.FindDriverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDriver", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindDriverResponse> FindDriverAsync(WebClient.ServiceReference1.FindDriverRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindDriverByAuthResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDriverByAuth", ReplyAction="*")]
        WebClient.ServiceReference1.FindDriverByAuthResponse FindDriverByAuth(WebClient.ServiceReference1.FindDriverByAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindDriverByAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindDriverByAuthResponse> FindDriverByAuthAsync(WebClient.ServiceReference1.FindDriverByAuthRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindAuthResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAuth", ReplyAction="*")]
        WebClient.ServiceReference1.FindAuthResponse FindAuth(WebClient.ServiceReference1.FindAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindAuthResponse> FindAuthAsync(WebClient.ServiceReference1.FindAuthRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем FindOrderResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindOrder", ReplyAction="*")]
        WebClient.ServiceReference1.FindOrderResponse FindOrder(WebClient.ServiceReference1.FindOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindOrderResponse> FindOrderAsync(WebClient.ServiceReference1.FindOrderRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем auth из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCustomerProfile", ReplyAction="*")]
        WebClient.ServiceReference1.EditCustomerProfileResponse EditCustomerProfile(WebClient.ServiceReference1.EditCustomerProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCustomerProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.EditCustomerProfileResponse> EditCustomerProfileAsync(WebClient.ServiceReference1.EditCustomerProfileRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем auth из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditDriverProfile", ReplyAction="*")]
        WebClient.ServiceReference1.EditDriverProfileResponse EditDriverProfile(WebClient.ServiceReference1.EditDriverProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditDriverProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.EditDriverProfileResponse> EditDriverProfileAsync(WebClient.ServiceReference1.EditDriverProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateDriverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateDriver", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.RegistrateDriverRequestBody Body;
        
        public RegistrateDriverRequest() {
        }
        
        public RegistrateDriverRequest(WebClient.ServiceReference1.RegistrateDriverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateDriverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string driver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authorization;
        
        public RegistrateDriverRequestBody() {
        }
        
        public RegistrateDriverRequestBody(string driver, string authorization) {
            this.driver = driver;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateDriverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateDriverResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.RegistrateDriverResponseBody Body;
        
        public RegistrateDriverResponse() {
        }
        
        public RegistrateDriverResponse(WebClient.ServiceReference1.RegistrateDriverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateDriverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrateDriverResult;
        
        public RegistrateDriverResponseBody() {
        }
        
        public RegistrateDriverResponseBody(bool RegistrateDriverResult) {
            this.RegistrateDriverResult = RegistrateDriverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.RegistrateCustomerRequestBody Body;
        
        public RegistrateCustomerRequest() {
        }
        
        public RegistrateCustomerRequest(WebClient.ServiceReference1.RegistrateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authorization;
        
        public RegistrateCustomerRequestBody() {
        }
        
        public RegistrateCustomerRequestBody(string customer, string authorization) {
            this.customer = customer;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.RegistrateCustomerResponseBody Body;
        
        public RegistrateCustomerResponse() {
        }
        
        public RegistrateCustomerResponse(WebClient.ServiceReference1.RegistrateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrateCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrateCustomerResult;
        
        public RegistrateCustomerResponseBody() {
        }
        
        public RegistrateCustomerResponseBody(bool RegistrateCustomerResult) {
            this.RegistrateCustomerResult = RegistrateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorize", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.AuthorizeRequestBody Body;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(WebClient.ServiceReference1.AuthorizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorization;
        
        public AuthorizeRequestBody() {
        }
        
        public AuthorizeRequestBody(string authorization) {
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.AuthorizeResponseBody Body;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(WebClient.ServiceReference1.AuthorizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid AuthorizeResult;
        
        public AuthorizeResponseBody() {
        }
        
        public AuthorizeResponseBody(System.Guid AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrders", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.GetListOfOrdersRequestBody Body;
        
        public GetListOfOrdersRequest() {
        }
        
        public GetListOfOrdersRequest(WebClient.ServiceReference1.GetListOfOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListOfOrdersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int role;
        
        public GetListOfOrdersRequestBody() {
        }
        
        public GetListOfOrdersRequestBody(System.Guid idClient, int role) {
            this.idClient = idClient;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListOfOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListOfOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.GetListOfOrdersResponseBody Body;
        
        public GetListOfOrdersResponse() {
        }
        
        public GetListOfOrdersResponse(WebClient.ServiceReference1.GetListOfOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListOfOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListOfOrdersResult;
        
        public GetListOfOrdersResponseBody() {
        }
        
        public GetListOfOrdersResponseBody(string GetListOfOrdersResult) {
            this.GetListOfOrdersResult = GetListOfOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.CreateOrderRequestBody Body;
        
        public CreateOrderRequest() {
        }
        
        public CreateOrderRequest(WebClient.ServiceReference1.CreateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string order;
        
        public CreateOrderRequestBody() {
        }
        
        public CreateOrderRequestBody(string order) {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.CreateOrderResponseBody Body;
        
        public CreateOrderResponse() {
        }
        
        public CreateOrderResponse(WebClient.ServiceReference1.CreateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateOrderResponseBody {
        
        public CreateOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ShowOrderRequestBody Body;
        
        public ShowOrderRequest() {
        }
        
        public ShowOrderRequest(WebClient.ServiceReference1.ShowOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<System.Guid> idClient;
        
        public ShowOrderRequestBody() {
        }
        
        public ShowOrderRequestBody(System.Nullable<System.Guid> idClient) {
            this.idClient = idClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ShowOrderResponseBody Body;
        
        public ShowOrderResponse() {
        }
        
        public ShowOrderResponse(WebClient.ServiceReference1.ShowOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowOrderResult;
        
        public ShowOrderResponseBody() {
        }
        
        public ShowOrderResponseBody(string ShowOrderResult) {
            this.ShowOrderResult = ShowOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDriverNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDriverNumber", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.GetDriverNumberRequestBody Body;
        
        public GetDriverNumberRequest() {
        }
        
        public GetDriverNumberRequest(WebClient.ServiceReference1.GetDriverNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDriverNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idOrder;
        
        public GetDriverNumberRequestBody() {
        }
        
        public GetDriverNumberRequestBody(System.Guid idOrder) {
            this.idOrder = idOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDriverNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDriverNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.GetDriverNumberResponseBody Body;
        
        public GetDriverNumberResponse() {
        }
        
        public GetDriverNumberResponse(WebClient.ServiceReference1.GetDriverNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDriverNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDriverNumberResult;
        
        public GetDriverNumberResponseBody() {
        }
        
        public GetDriverNumberResponseBody(string GetDriverNumberResult) {
            this.GetDriverNumberResult = GetDriverNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCustomer", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindCustomerRequestBody Body;
        
        public FindCustomerRequest() {
        }
        
        public FindCustomerRequest(WebClient.ServiceReference1.FindCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idCustomer;
        
        public FindCustomerRequestBody() {
        }
        
        public FindCustomerRequestBody(System.Guid idCustomer) {
            this.idCustomer = idCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindCustomerResponseBody Body;
        
        public FindCustomerResponse() {
        }
        
        public FindCustomerResponse(WebClient.ServiceReference1.FindCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindCustomerResult;
        
        public FindCustomerResponseBody() {
        }
        
        public FindCustomerResponseBody(string FindCustomerResult) {
            this.FindCustomerResult = FindCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDriverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDriver", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindDriverRequestBody Body;
        
        public FindDriverRequest() {
        }
        
        public FindDriverRequest(WebClient.ServiceReference1.FindDriverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDriverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idDriver;
        
        public FindDriverRequestBody() {
        }
        
        public FindDriverRequestBody(System.Guid idDriver) {
            this.idDriver = idDriver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDriverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDriverResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindDriverResponseBody Body;
        
        public FindDriverResponse() {
        }
        
        public FindDriverResponse(WebClient.ServiceReference1.FindDriverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDriverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindDriverResult;
        
        public FindDriverResponseBody() {
        }
        
        public FindDriverResponseBody(string FindDriverResult) {
            this.FindDriverResult = FindDriverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDriverByAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDriverByAuth", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindDriverByAuthRequestBody Body;
        
        public FindDriverByAuthRequest() {
        }
        
        public FindDriverByAuthRequest(WebClient.ServiceReference1.FindDriverByAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDriverByAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid idAuth;
        
        public FindDriverByAuthRequestBody() {
        }
        
        public FindDriverByAuthRequestBody(System.Guid idAuth) {
            this.idAuth = idAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDriverByAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDriverByAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindDriverByAuthResponseBody Body;
        
        public FindDriverByAuthResponse() {
        }
        
        public FindDriverByAuthResponse(WebClient.ServiceReference1.FindDriverByAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindDriverByAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindDriverByAuthResult;
        
        public FindDriverByAuthResponseBody() {
        }
        
        public FindDriverByAuthResponseBody(string FindDriverByAuthResult) {
            this.FindDriverByAuthResult = FindDriverByAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAuth", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindAuthRequestBody Body;
        
        public FindAuthRequest() {
        }
        
        public FindAuthRequest(WebClient.ServiceReference1.FindAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public FindAuthRequestBody() {
        }
        
        public FindAuthRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindAuthResponseBody Body;
        
        public FindAuthResponse() {
        }
        
        public FindAuthResponse(WebClient.ServiceReference1.FindAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindAuthResult;
        
        public FindAuthResponseBody() {
        }
        
        public FindAuthResponseBody(string FindAuthResult) {
            this.FindAuthResult = FindAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindOrderRequestBody Body;
        
        public FindOrderRequest() {
        }
        
        public FindOrderRequest(WebClient.ServiceReference1.FindOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public FindOrderRequestBody() {
        }
        
        public FindOrderRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.FindOrderResponseBody Body;
        
        public FindOrderResponse() {
        }
        
        public FindOrderResponse(WebClient.ServiceReference1.FindOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindOrderResult;
        
        public FindOrderResponseBody() {
        }
        
        public FindOrderResponseBody(string FindOrderResult) {
            this.FindOrderResult = FindOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCustomerProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCustomerProfile", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.EditCustomerProfileRequestBody Body;
        
        public EditCustomerProfileRequest() {
        }
        
        public EditCustomerProfileRequest(WebClient.ServiceReference1.EditCustomerProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCustomerProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer;
        
        public EditCustomerProfileRequestBody() {
        }
        
        public EditCustomerProfileRequestBody(string auth, string customer) {
            this.auth = auth;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditCustomerProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditCustomerProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.EditCustomerProfileResponseBody Body;
        
        public EditCustomerProfileResponse() {
        }
        
        public EditCustomerProfileResponse(WebClient.ServiceReference1.EditCustomerProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditCustomerProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditCustomerProfileResult;
        
        public EditCustomerProfileResponseBody() {
        }
        
        public EditCustomerProfileResponseBody(bool EditCustomerProfileResult) {
            this.EditCustomerProfileResult = EditCustomerProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDriverProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDriverProfile", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.EditDriverProfileRequestBody Body;
        
        public EditDriverProfileRequest() {
        }
        
        public EditDriverProfileRequest(WebClient.ServiceReference1.EditDriverProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditDriverProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string driver;
        
        public EditDriverProfileRequestBody() {
        }
        
        public EditDriverProfileRequestBody(string auth, string driver) {
            this.auth = auth;
            this.driver = driver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditDriverProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditDriverProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.EditDriverProfileResponseBody Body;
        
        public EditDriverProfileResponse() {
        }
        
        public EditDriverProfileResponse(WebClient.ServiceReference1.EditDriverProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditDriverProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditDriverProfileResult;
        
        public EditDriverProfileResponseBody() {
        }
        
        public EditDriverProfileResponseBody(bool EditDriverProfileResult) {
            this.EditDriverProfileResult = EditDriverProfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTaxiSoapChannel : WebClient.ServiceReference1.WebServiceTaxiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTaxiSoapClient : System.ServiceModel.ClientBase<WebClient.ServiceReference1.WebServiceTaxiSoap>, WebClient.ServiceReference1.WebServiceTaxiSoap {
        
        public WebServiceTaxiSoapClient() {
        }
        
        public WebServiceTaxiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTaxiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTaxiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTaxiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.RegistrateDriverResponse WebClient.ServiceReference1.WebServiceTaxiSoap.RegistrateDriver(WebClient.ServiceReference1.RegistrateDriverRequest request) {
            return base.Channel.RegistrateDriver(request);
        }
        
        public bool RegistrateDriver(string driver, string authorization) {
            WebClient.ServiceReference1.RegistrateDriverRequest inValue = new WebClient.ServiceReference1.RegistrateDriverRequest();
            inValue.Body = new WebClient.ServiceReference1.RegistrateDriverRequestBody();
            inValue.Body.driver = driver;
            inValue.Body.authorization = authorization;
            WebClient.ServiceReference1.RegistrateDriverResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateDriver(inValue);
            return retVal.Body.RegistrateDriverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.RegistrateDriverResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.RegistrateDriverAsync(WebClient.ServiceReference1.RegistrateDriverRequest request) {
            return base.Channel.RegistrateDriverAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.RegistrateDriverResponse> RegistrateDriverAsync(string driver, string authorization) {
            WebClient.ServiceReference1.RegistrateDriverRequest inValue = new WebClient.ServiceReference1.RegistrateDriverRequest();
            inValue.Body = new WebClient.ServiceReference1.RegistrateDriverRequestBody();
            inValue.Body.driver = driver;
            inValue.Body.authorization = authorization;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateDriverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.RegistrateCustomerResponse WebClient.ServiceReference1.WebServiceTaxiSoap.RegistrateCustomer(WebClient.ServiceReference1.RegistrateCustomerRequest request) {
            return base.Channel.RegistrateCustomer(request);
        }
        
        public bool RegistrateCustomer(string customer, string authorization) {
            WebClient.ServiceReference1.RegistrateCustomerRequest inValue = new WebClient.ServiceReference1.RegistrateCustomerRequest();
            inValue.Body = new WebClient.ServiceReference1.RegistrateCustomerRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.authorization = authorization;
            WebClient.ServiceReference1.RegistrateCustomerResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateCustomer(inValue);
            return retVal.Body.RegistrateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.RegistrateCustomerResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.RegistrateCustomerAsync(WebClient.ServiceReference1.RegistrateCustomerRequest request) {
            return base.Channel.RegistrateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.RegistrateCustomerResponse> RegistrateCustomerAsync(string customer, string authorization) {
            WebClient.ServiceReference1.RegistrateCustomerRequest inValue = new WebClient.ServiceReference1.RegistrateCustomerRequest();
            inValue.Body = new WebClient.ServiceReference1.RegistrateCustomerRequestBody();
            inValue.Body.customer = customer;
            inValue.Body.authorization = authorization;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).RegistrateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.AuthorizeResponse WebClient.ServiceReference1.WebServiceTaxiSoap.Authorize(WebClient.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public System.Guid Authorize(string authorization) {
            WebClient.ServiceReference1.AuthorizeRequest inValue = new WebClient.ServiceReference1.AuthorizeRequest();
            inValue.Body = new WebClient.ServiceReference1.AuthorizeRequestBody();
            inValue.Body.authorization = authorization;
            WebClient.ServiceReference1.AuthorizeResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).Authorize(inValue);
            return retVal.Body.AuthorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.AuthorizeResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.AuthorizeAsync(WebClient.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.AuthorizeResponse> AuthorizeAsync(string authorization) {
            WebClient.ServiceReference1.AuthorizeRequest inValue = new WebClient.ServiceReference1.AuthorizeRequest();
            inValue.Body = new WebClient.ServiceReference1.AuthorizeRequestBody();
            inValue.Body.authorization = authorization;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).AuthorizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.GetListOfOrdersResponse WebClient.ServiceReference1.WebServiceTaxiSoap.GetListOfOrders(WebClient.ServiceReference1.GetListOfOrdersRequest request) {
            return base.Channel.GetListOfOrders(request);
        }
        
        public string GetListOfOrders(System.Guid idClient, int role) {
            WebClient.ServiceReference1.GetListOfOrdersRequest inValue = new WebClient.ServiceReference1.GetListOfOrdersRequest();
            inValue.Body = new WebClient.ServiceReference1.GetListOfOrdersRequestBody();
            inValue.Body.idClient = idClient;
            inValue.Body.role = role;
            WebClient.ServiceReference1.GetListOfOrdersResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetListOfOrders(inValue);
            return retVal.Body.GetListOfOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.GetListOfOrdersResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.GetListOfOrdersAsync(WebClient.ServiceReference1.GetListOfOrdersRequest request) {
            return base.Channel.GetListOfOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.GetListOfOrdersResponse> GetListOfOrdersAsync(System.Guid idClient, int role) {
            WebClient.ServiceReference1.GetListOfOrdersRequest inValue = new WebClient.ServiceReference1.GetListOfOrdersRequest();
            inValue.Body = new WebClient.ServiceReference1.GetListOfOrdersRequestBody();
            inValue.Body.idClient = idClient;
            inValue.Body.role = role;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetListOfOrdersAsync(inValue);
        }
        
        public void GetOrder(System.Guid idDriver, System.Guid idOrder) {
            base.Channel.GetOrder(idDriver, idOrder);
        }
        
        public System.Threading.Tasks.Task GetOrderAsync(System.Guid idDriver, System.Guid idOrder) {
            return base.Channel.GetOrderAsync(idDriver, idOrder);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.CreateOrderResponse WebClient.ServiceReference1.WebServiceTaxiSoap.CreateOrder(WebClient.ServiceReference1.CreateOrderRequest request) {
            return base.Channel.CreateOrder(request);
        }
        
        public void CreateOrder(string order) {
            WebClient.ServiceReference1.CreateOrderRequest inValue = new WebClient.ServiceReference1.CreateOrderRequest();
            inValue.Body = new WebClient.ServiceReference1.CreateOrderRequestBody();
            inValue.Body.order = order;
            WebClient.ServiceReference1.CreateOrderResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).CreateOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.CreateOrderResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.CreateOrderAsync(WebClient.ServiceReference1.CreateOrderRequest request) {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.CreateOrderResponse> CreateOrderAsync(string order) {
            WebClient.ServiceReference1.CreateOrderRequest inValue = new WebClient.ServiceReference1.CreateOrderRequest();
            inValue.Body = new WebClient.ServiceReference1.CreateOrderRequestBody();
            inValue.Body.order = order;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).CreateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.ShowOrderResponse WebClient.ServiceReference1.WebServiceTaxiSoap.ShowOrder(WebClient.ServiceReference1.ShowOrderRequest request) {
            return base.Channel.ShowOrder(request);
        }
        
        public string ShowOrder(System.Nullable<System.Guid> idClient) {
            WebClient.ServiceReference1.ShowOrderRequest inValue = new WebClient.ServiceReference1.ShowOrderRequest();
            inValue.Body = new WebClient.ServiceReference1.ShowOrderRequestBody();
            inValue.Body.idClient = idClient;
            WebClient.ServiceReference1.ShowOrderResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).ShowOrder(inValue);
            return retVal.Body.ShowOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ShowOrderResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.ShowOrderAsync(WebClient.ServiceReference1.ShowOrderRequest request) {
            return base.Channel.ShowOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.ShowOrderResponse> ShowOrderAsync(System.Nullable<System.Guid> idClient) {
            WebClient.ServiceReference1.ShowOrderRequest inValue = new WebClient.ServiceReference1.ShowOrderRequest();
            inValue.Body = new WebClient.ServiceReference1.ShowOrderRequestBody();
            inValue.Body.idClient = idClient;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).ShowOrderAsync(inValue);
        }
        
        public void CancellationOfOrder(System.Guid idClient, System.Guid idOrder) {
            base.Channel.CancellationOfOrder(idClient, idOrder);
        }
        
        public System.Threading.Tasks.Task CancellationOfOrderAsync(System.Guid idClient, System.Guid idOrder) {
            return base.Channel.CancellationOfOrderAsync(idClient, idOrder);
        }
        
        public void StartTrip(System.Guid idDriver, System.Guid idOrder) {
            base.Channel.StartTrip(idDriver, idOrder);
        }
        
        public System.Threading.Tasks.Task StartTripAsync(System.Guid idDriver, System.Guid idOrder) {
            return base.Channel.StartTripAsync(idDriver, idOrder);
        }
        
        public void FinishTrip(System.Guid idDriver, System.Guid idOrder) {
            base.Channel.FinishTrip(idDriver, idOrder);
        }
        
        public System.Threading.Tasks.Task FinishTripAsync(System.Guid idDriver, System.Guid idOrder) {
            return base.Channel.FinishTripAsync(idDriver, idOrder);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.GetDriverNumberResponse WebClient.ServiceReference1.WebServiceTaxiSoap.GetDriverNumber(WebClient.ServiceReference1.GetDriverNumberRequest request) {
            return base.Channel.GetDriverNumber(request);
        }
        
        public string GetDriverNumber(System.Guid idOrder) {
            WebClient.ServiceReference1.GetDriverNumberRequest inValue = new WebClient.ServiceReference1.GetDriverNumberRequest();
            inValue.Body = new WebClient.ServiceReference1.GetDriverNumberRequestBody();
            inValue.Body.idOrder = idOrder;
            WebClient.ServiceReference1.GetDriverNumberResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetDriverNumber(inValue);
            return retVal.Body.GetDriverNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.GetDriverNumberResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.GetDriverNumberAsync(WebClient.ServiceReference1.GetDriverNumberRequest request) {
            return base.Channel.GetDriverNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.GetDriverNumberResponse> GetDriverNumberAsync(System.Guid idOrder) {
            WebClient.ServiceReference1.GetDriverNumberRequest inValue = new WebClient.ServiceReference1.GetDriverNumberRequest();
            inValue.Body = new WebClient.ServiceReference1.GetDriverNumberRequestBody();
            inValue.Body.idOrder = idOrder;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).GetDriverNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.FindCustomerResponse WebClient.ServiceReference1.WebServiceTaxiSoap.FindCustomer(WebClient.ServiceReference1.FindCustomerRequest request) {
            return base.Channel.FindCustomer(request);
        }
        
        public string FindCustomer(System.Guid idCustomer) {
            WebClient.ServiceReference1.FindCustomerRequest inValue = new WebClient.ServiceReference1.FindCustomerRequest();
            inValue.Body = new WebClient.ServiceReference1.FindCustomerRequestBody();
            inValue.Body.idCustomer = idCustomer;
            WebClient.ServiceReference1.FindCustomerResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindCustomer(inValue);
            return retVal.Body.FindCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindCustomerResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.FindCustomerAsync(WebClient.ServiceReference1.FindCustomerRequest request) {
            return base.Channel.FindCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.FindCustomerResponse> FindCustomerAsync(System.Guid idCustomer) {
            WebClient.ServiceReference1.FindCustomerRequest inValue = new WebClient.ServiceReference1.FindCustomerRequest();
            inValue.Body = new WebClient.ServiceReference1.FindCustomerRequestBody();
            inValue.Body.idCustomer = idCustomer;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.FindDriverResponse WebClient.ServiceReference1.WebServiceTaxiSoap.FindDriver(WebClient.ServiceReference1.FindDriverRequest request) {
            return base.Channel.FindDriver(request);
        }
        
        public string FindDriver(System.Guid idDriver) {
            WebClient.ServiceReference1.FindDriverRequest inValue = new WebClient.ServiceReference1.FindDriverRequest();
            inValue.Body = new WebClient.ServiceReference1.FindDriverRequestBody();
            inValue.Body.idDriver = idDriver;
            WebClient.ServiceReference1.FindDriverResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindDriver(inValue);
            return retVal.Body.FindDriverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindDriverResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.FindDriverAsync(WebClient.ServiceReference1.FindDriverRequest request) {
            return base.Channel.FindDriverAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.FindDriverResponse> FindDriverAsync(System.Guid idDriver) {
            WebClient.ServiceReference1.FindDriverRequest inValue = new WebClient.ServiceReference1.FindDriverRequest();
            inValue.Body = new WebClient.ServiceReference1.FindDriverRequestBody();
            inValue.Body.idDriver = idDriver;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindDriverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.FindDriverByAuthResponse WebClient.ServiceReference1.WebServiceTaxiSoap.FindDriverByAuth(WebClient.ServiceReference1.FindDriverByAuthRequest request) {
            return base.Channel.FindDriverByAuth(request);
        }
        
        public string FindDriverByAuth(System.Guid idAuth) {
            WebClient.ServiceReference1.FindDriverByAuthRequest inValue = new WebClient.ServiceReference1.FindDriverByAuthRequest();
            inValue.Body = new WebClient.ServiceReference1.FindDriverByAuthRequestBody();
            inValue.Body.idAuth = idAuth;
            WebClient.ServiceReference1.FindDriverByAuthResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindDriverByAuth(inValue);
            return retVal.Body.FindDriverByAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindDriverByAuthResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.FindDriverByAuthAsync(WebClient.ServiceReference1.FindDriverByAuthRequest request) {
            return base.Channel.FindDriverByAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.FindDriverByAuthResponse> FindDriverByAuthAsync(System.Guid idAuth) {
            WebClient.ServiceReference1.FindDriverByAuthRequest inValue = new WebClient.ServiceReference1.FindDriverByAuthRequest();
            inValue.Body = new WebClient.ServiceReference1.FindDriverByAuthRequestBody();
            inValue.Body.idAuth = idAuth;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindDriverByAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.FindAuthResponse WebClient.ServiceReference1.WebServiceTaxiSoap.FindAuth(WebClient.ServiceReference1.FindAuthRequest request) {
            return base.Channel.FindAuth(request);
        }
        
        public string FindAuth(System.Guid id) {
            WebClient.ServiceReference1.FindAuthRequest inValue = new WebClient.ServiceReference1.FindAuthRequest();
            inValue.Body = new WebClient.ServiceReference1.FindAuthRequestBody();
            inValue.Body.id = id;
            WebClient.ServiceReference1.FindAuthResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindAuth(inValue);
            return retVal.Body.FindAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindAuthResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.FindAuthAsync(WebClient.ServiceReference1.FindAuthRequest request) {
            return base.Channel.FindAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.FindAuthResponse> FindAuthAsync(System.Guid id) {
            WebClient.ServiceReference1.FindAuthRequest inValue = new WebClient.ServiceReference1.FindAuthRequest();
            inValue.Body = new WebClient.ServiceReference1.FindAuthRequestBody();
            inValue.Body.id = id;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.FindOrderResponse WebClient.ServiceReference1.WebServiceTaxiSoap.FindOrder(WebClient.ServiceReference1.FindOrderRequest request) {
            return base.Channel.FindOrder(request);
        }
        
        public string FindOrder(System.Guid id) {
            WebClient.ServiceReference1.FindOrderRequest inValue = new WebClient.ServiceReference1.FindOrderRequest();
            inValue.Body = new WebClient.ServiceReference1.FindOrderRequestBody();
            inValue.Body.id = id;
            WebClient.ServiceReference1.FindOrderResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindOrder(inValue);
            return retVal.Body.FindOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.FindOrderResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.FindOrderAsync(WebClient.ServiceReference1.FindOrderRequest request) {
            return base.Channel.FindOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.FindOrderResponse> FindOrderAsync(System.Guid id) {
            WebClient.ServiceReference1.FindOrderRequest inValue = new WebClient.ServiceReference1.FindOrderRequest();
            inValue.Body = new WebClient.ServiceReference1.FindOrderRequestBody();
            inValue.Body.id = id;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).FindOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.EditCustomerProfileResponse WebClient.ServiceReference1.WebServiceTaxiSoap.EditCustomerProfile(WebClient.ServiceReference1.EditCustomerProfileRequest request) {
            return base.Channel.EditCustomerProfile(request);
        }
        
        public bool EditCustomerProfile(string auth, string customer) {
            WebClient.ServiceReference1.EditCustomerProfileRequest inValue = new WebClient.ServiceReference1.EditCustomerProfileRequest();
            inValue.Body = new WebClient.ServiceReference1.EditCustomerProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.customer = customer;
            WebClient.ServiceReference1.EditCustomerProfileResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditCustomerProfile(inValue);
            return retVal.Body.EditCustomerProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.EditCustomerProfileResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.EditCustomerProfileAsync(WebClient.ServiceReference1.EditCustomerProfileRequest request) {
            return base.Channel.EditCustomerProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.EditCustomerProfileResponse> EditCustomerProfileAsync(string auth, string customer) {
            WebClient.ServiceReference1.EditCustomerProfileRequest inValue = new WebClient.ServiceReference1.EditCustomerProfileRequest();
            inValue.Body = new WebClient.ServiceReference1.EditCustomerProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.customer = customer;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditCustomerProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.EditDriverProfileResponse WebClient.ServiceReference1.WebServiceTaxiSoap.EditDriverProfile(WebClient.ServiceReference1.EditDriverProfileRequest request) {
            return base.Channel.EditDriverProfile(request);
        }
        
        public bool EditDriverProfile(string auth, string driver) {
            WebClient.ServiceReference1.EditDriverProfileRequest inValue = new WebClient.ServiceReference1.EditDriverProfileRequest();
            inValue.Body = new WebClient.ServiceReference1.EditDriverProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.driver = driver;
            WebClient.ServiceReference1.EditDriverProfileResponse retVal = ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditDriverProfile(inValue);
            return retVal.Body.EditDriverProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.EditDriverProfileResponse> WebClient.ServiceReference1.WebServiceTaxiSoap.EditDriverProfileAsync(WebClient.ServiceReference1.EditDriverProfileRequest request) {
            return base.Channel.EditDriverProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.EditDriverProfileResponse> EditDriverProfileAsync(string auth, string driver) {
            WebClient.ServiceReference1.EditDriverProfileRequest inValue = new WebClient.ServiceReference1.EditDriverProfileRequest();
            inValue.Body = new WebClient.ServiceReference1.EditDriverProfileRequestBody();
            inValue.Body.auth = auth;
            inValue.Body.driver = driver;
            return ((WebClient.ServiceReference1.WebServiceTaxiSoap)(this)).EditDriverProfileAsync(inValue);
        }
    }
}
